### PR TITLE
Added router public/index.php

### PR DESCRIPTION
**Pull request by djnotes**
Seems like the public/index.php router is needed to run the project for development. So added the router to the composer serve command.

|    Q          |   A
|-------------- | ------

| Bugfix        | yes

### Description

Without passing the router script (index.php) on the composer command, the project does not load properly.

### CODE REVIEW

**Review by michalbundyra — CHANGES_REQUESTED** [review]
@djnotes thanks for your contribution.

As I remember we had issues with this line multiple times, and I believe it was the last version which suppose to work everywhere. Would you be able to provide more information, please?

- php version
- composer version
- your OS

I've checked our other project and we have the same there, and I haven't seen any issue reports any time recently - see for example: https://github.com/mezzio/mezzio-skeleton/blob/3.6.x/composer.json#L107

Thanks!

**Comment by weierophinney** [comment]
@michalbundyra I just verified that this fails on each of 7.1 - 7.4 for certain; I didn't bother trying 5.6 or 7.0, as doing so was going to require re-installing requirements (I'd originally created a project using 7.3). As such, I think we should merge. It's not a huge change, and we've had it before, so I think it falls under the "obvious fix" category.

**Comment by michalbundyra** [comment]
@weierophinney as it is failing here I guess it is also failing in mezzio, but... I haven't seen any reports there...

**Comment by weierophinney** [comment]
@michalbundyra The difference here is that we have _local assets_ associated with the skeleton, while the other skeletons do not.

**Pull request merged**
